restaurants = [
    'Blaze Pizza',
    'Buffalo Wild Wings',
    'Cafe Istanbul',
    'Cane Rosso',
    'Chipotle',
    'Chuys',
    'Fadis',
    'La Hacienda',
    'Liberty Burger',
    'Hutchins',
    'Mi Cocina',
    'Macaroni Grill',
    'Piadas',
    'Raising Canes',
    'Rudys BBQ',
    'Schlotzkys',
    'Texas Kabob House',
    'Tight Ends',
    'Taverna Rossa',
    'Twin Peaks',
    'Platias',
    'Village Burger',
    'Wild Pitch',
    'Wingstop'
]
